services:
  windows-canvas-docker:
    build:
      context: .
      dockerfile: Dockerfile.windows
    command: sleep infinity #/canvas-source-code/windows.entrypoint.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/canvas-source-code
