common: &common
  adapter: postgresql
  host: <%= ENV.fetch('CANVAS_DATABASE_HOST', 'localhost') %>
  username: <%= ENV.fetch('CANVAS_DATABASE_USERNAME', 'canvas') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'canvas') %>
  encoding: utf8
  timeout: 5000
  prepared_statements: false
  use_qualified_names: true
  shard_name: public
  schema_search_path: "''"

production:
  <<: *common
  database: canvas_production

development:
  <<: *common
  database: canvas_development

test:
  <<: *common
  database: canvas_test
