production: &default
  url: redis://localhost
  connect_timeout: 0.5
  circuit_breaker:
    error_threshold: 1
    error_timeout: 2

development:
  <<: *default

test:
  url: redis://localhost/1
  connect_timeout: 0.5
